---
deployment:
  tasks:
    - export DEPLOYPATH=/home/britaszk/public_html/
    - /home/britaszk/repositories/bin/cp index.html $DEPLOYPATH
    - /home/britaszk/repositories/bin/cp style.css $DEPLOYPATH